### ISSUE TITLE
Implementation for App Center

### ISSUE THREAD

**Issue by DarryStonem** [xamarin-automation-service/Appium.POP.Example#5]
Hi! 

Just to let you know that I made a couple of changes in my own repository based on this project to use App Center: [https://github.com/DarryStonem/Appium-AppCenter-Example](https://github.com/DarryStonem/Appium-AppCenter-Example).

I changed some code for the support. And is running correctly.

**Comment by MatisseHack** [comment]
Awesome! Do you think you fixed the same issue mentioned in #4?

It would be great if you wanted to fork this repo and submit a pull request with your changes!

**Comment by DarryStonem** [comment]
@MatisseHack Sure, I'll submit the PR 😀, and the #4 is from a coworker, so yes.

**Comment by DarryStonem** [comment]
@MatisseHack : I just pushed the PR 😄 https://github.com/xamarin-automation-service/Appium.POP.Example/pull/6
